### ISSUE TITLE
"blue screens" on android 4.1 with chrome for Android 

### ISSUE THREAD

**Issue by morkeleb** [agical/friendsunhosted#31]
Just did a short test where I followed a link from twitter and the page didn't load. Just the Blue background.

**Comment by jancborchardt** [comment]
This is probably because of the Javascripts being in the head and blocking loading of the page. require.js takes ~14 seconds on my machine (people normally quit the app after 10s of waiting max).

@brolund we should put the Javascript last thing on the page so that the HTML & CSS will display before as indication something happens.

**Comment by morkeleb** [comment]
This is a very probable cause.

**Comment by brolund** [comment]
Interesting. On my HTC standard browser on Android 4 it all works fine, and almost as fast as on my laptop. On Chrome in the same phone it freezes when abt half the page is rendered, and then nothing happens. 

Not saying we won't try to fix it ;-) , just weird that it is so different...

**Comment by brolund** [comment]
Weird. After typing some in the url of the Chrome browser, and then getting back to the first page, it works fine. Any ideas?

**Comment by brolund** [comment]
@morkeleb Can you try the new version? It should be much nicer to mobile devices. It seems to work pretty fine in both Chrome and the default HTC browser (granted, on my 4 kernel HTC, but anyways... ;-))

**Comment by morkeleb** [comment]
Seems to work now. Still get a text that says loading when loading is done.
But it is much faster.

**Comment by brolund** [comment]
Excellent! I'll close this.
