### ISSUE TITLE
Same fontsize for thread-text and comments?

### ISSUE THREAD

**Issue by johlrogge** [agical/friendsunhosted#51]
As it is now the thread-text has 16px and comments have 13px (or actually 0.8em which on my screen becomes 13px). It looks like this is part of the problem why indentation looks weird on narrow screens (such as iPhones) and I think it looks nice in general if both texts have the same size.

Does anyone share my opinion on this?

**Comment by jancborchardt** [comment]
The indentation problem is probably because em are used. We should use px wherever possible because they allow us to set things absolutely, whereas em are dependent on the font size and change all child element metrics.

The text size difference in general should stay though, it’s a good instant indicator of what the text you’re reading is.

**Comment by johlrogge** [comment]
The new design released today solves this issue for me. Closing
